name: desk_tattoo
description: "Application mobile DesK Tattoo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Networking
  dio: ^5.7.0

  # Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # Environment
  flutter_dotenv: ^5.2.1

  # i18n
  intl: any
  timezone: ^0.11.0
  pdf: ^3.13.0
  printing: ^5.15.0
  path_provider: ^2.1.6
  qr_flutter: ^4.1.0
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.2
  signature: ^6.4.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Codegen
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icon/app_icon.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/app_icon.png
  min_sdk_android: 24
